-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor\monitor_dut.vhd
-- Created: 2022-08-30 10:16:39
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: monitor_dut
-- Source Path: monitor/monitor_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY monitor_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        dataWriteAXI0                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI1                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI2                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI3                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI4                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI5                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI6                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWriteAXI7                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataRead7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        dataWrite0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite6                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataWrite7                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataReadAXI7                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END monitor_dut;


ARCHITECTURE rtl OF monitor_dut IS

  -- Component Declarations
  COMPONENT monitor_src_monitor
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataWriteAXI0                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI1                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI2                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI3                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI4                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI5                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI6                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWriteAXI7                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead0                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead1                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead2                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead3                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead4                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead5                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead6                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataRead7                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          dataWrite0                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite1                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite2                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite3                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite4                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite5                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite6                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataWrite7                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI0                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI1                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI2                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI3                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI4                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI5                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI6                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataReadAXI7                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : monitor_src_monitor
    USE ENTITY work.monitor_src_monitor(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL dataWrite0_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite1_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite2_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite3_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite4_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite5_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite6_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataWrite7_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI0_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI1_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI2_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI3_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI4_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI5_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI6_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataReadAXI7_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_monitor_src_monitor : monitor_src_monitor
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              dataWriteAXI0 => dataWriteAXI0,  -- ufix32
              dataWriteAXI1 => dataWriteAXI1,  -- ufix32
              dataWriteAXI2 => dataWriteAXI2,  -- ufix32
              dataWriteAXI3 => dataWriteAXI3,  -- ufix32
              dataWriteAXI4 => dataWriteAXI4,  -- ufix32
              dataWriteAXI5 => dataWriteAXI5,  -- ufix32
              dataWriteAXI6 => dataWriteAXI6,  -- ufix32
              dataWriteAXI7 => dataWriteAXI7,  -- ufix32
              dataRead0 => dataRead0,  -- ufix32
              dataRead1 => dataRead1,  -- ufix32
              dataRead2 => dataRead2,  -- ufix32
              dataRead3 => dataRead3,  -- ufix32
              dataRead4 => dataRead4,  -- ufix32
              dataRead5 => dataRead5,  -- ufix32
              dataRead6 => dataRead6,  -- ufix32
              dataRead7 => dataRead7,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              dataWrite0 => dataWrite0_sig,  -- ufix32
              dataWrite1 => dataWrite1_sig,  -- ufix32
              dataWrite2 => dataWrite2_sig,  -- ufix32
              dataWrite3 => dataWrite3_sig,  -- ufix32
              dataWrite4 => dataWrite4_sig,  -- ufix32
              dataWrite5 => dataWrite5_sig,  -- ufix32
              dataWrite6 => dataWrite6_sig,  -- ufix32
              dataWrite7 => dataWrite7_sig,  -- ufix32
              dataReadAXI0 => dataReadAXI0_sig,  -- ufix32
              dataReadAXI1 => dataReadAXI1_sig,  -- ufix32
              dataReadAXI2 => dataReadAXI2_sig,  -- ufix32
              dataReadAXI3 => dataReadAXI3_sig,  -- ufix32
              dataReadAXI4 => dataReadAXI4_sig,  -- ufix32
              dataReadAXI5 => dataReadAXI5_sig,  -- ufix32
              dataReadAXI6 => dataReadAXI6_sig,  -- ufix32
              dataReadAXI7 => dataReadAXI7_sig  -- ufix32
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  dataWrite0 <= dataWrite0_sig;

  dataWrite1 <= dataWrite1_sig;

  dataWrite2 <= dataWrite2_sig;

  dataWrite3 <= dataWrite3_sig;

  dataWrite4 <= dataWrite4_sig;

  dataWrite5 <= dataWrite5_sig;

  dataWrite6 <= dataWrite6_sig;

  dataWrite7 <= dataWrite7_sig;

  dataReadAXI0 <= dataReadAXI0_sig;

  dataReadAXI1 <= dataReadAXI1_sig;

  dataReadAXI2 <= dataReadAXI2_sig;

  dataReadAXI3 <= dataReadAXI3_sig;

  dataReadAXI4 <= dataReadAXI4_sig;

  dataReadAXI5 <= dataReadAXI5_sig;

  dataReadAXI6 <= dataReadAXI6_sig;

  dataReadAXI7 <= dataReadAXI7_sig;

END rtl;

