-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor\txPacketGenerator_src_MATLAB_Function.vhd
-- Created: 2022-08-23 14:49:56
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: txPacketGenerator_src_MATLAB_Function
-- Source Path: monitor/monitor/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY txPacketGenerator_src_MATLAB_Function IS
  PORT( dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END txPacketGenerator_src_MATLAB_Function;


ARCHITECTURE rtl OF txPacketGenerator_src_MATLAB_Function IS

  -- Signals
  SIGNAL dataIn_unsigned                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL dataOut_tmp                      : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  dataIn_unsigned <= unsigned(dataIn);

  dataOut_tmp <= dataIn_unsigned;

  dataOut <= std_logic_vector(dataOut_tmp);

END rtl;

