-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor\txPacketGenerator_src_monitor.vhd
-- Created: 2022-08-23 14:49:56
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: txPacketGenerator_src_monitor
-- Source Path: monitor/monitor
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY txPacketGenerator_src_monitor IS
  PORT( dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END txPacketGenerator_src_monitor;


ARCHITECTURE rtl OF txPacketGenerator_src_monitor IS

  -- Component Declarations
  COMPONENT txPacketGenerator_src_MATLAB_Function
    PORT( dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : txPacketGenerator_src_MATLAB_Function
    USE ENTITY work.txPacketGenerator_src_MATLAB_Function(rtl);

  -- Signals
  SIGNAL dataOut_tmp                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_MATLAB_Function : txPacketGenerator_src_MATLAB_Function
    PORT MAP( dataIn => dataIn,  -- uint32
              dataOut => dataOut_tmp  -- uint32
              );

  dataOut <= dataOut_tmp;

END rtl;

