-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\monitor\txPacketGenerator_dut.vhd
-- Created: 2022-08-23 14:50:05
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: txPacketGenerator_dut
-- Source Path: txPacketGenerator/txPacketGenerator_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY txPacketGenerator_dut IS
  PORT( dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END txPacketGenerator_dut;


ARCHITECTURE rtl OF txPacketGenerator_dut IS

  -- Component Declarations
  COMPONENT txPacketGenerator_src_monitor
    PORT( dataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : txPacketGenerator_src_monitor
    USE ENTITY work.txPacketGenerator_src_monitor(rtl);

  -- Signals
  SIGNAL dataOut_sig                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_txPacketGenerator_src_monitor : txPacketGenerator_src_monitor
    PORT MAP( dataIn => dataIn,  -- ufix32
              dataOut => dataOut_sig  -- ufix32
              );

  dataOut <= dataOut_sig;

END rtl;

