-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\txPacketGenerator\txPacketGenerator.vhd
-- Created: 2022-08-30 11:59:58
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- m_tdata_re                    ce_out        1
-- m_tvalid_re                   ce_out        1
-- s_tready_re                   ce_out        1
-- m_tdata_im                    ce_out        1
-- m_tvalid_im                   ce_out        1
-- s_tready_im                   ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: txPacketGenerator
-- Source Path: txPacketGenerator/txPacketGenerator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY txPacketGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        packetSize                        :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        transferReady                     :   IN    std_logic;  -- ufix1
        s_tdata_re                        :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        s_tvalid_re                       :   IN    std_logic;  -- ufix1
        m_tready_re                       :   IN    std_logic;  -- ufix1
        s_tdata_im                        :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        s_tvalid_im                       :   IN    std_logic;  -- ufix1
        m_tready_im                       :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;
        m_tdata_re                        :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        m_tvalid_re                       :   OUT   std_logic;
        s_tready_re                       :   OUT   std_logic;
        m_tdata_im                        :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        m_tvalid_im                       :   OUT   std_logic;
        s_tready_im                       :   OUT   std_logic
        );
END txPacketGenerator;


ARCHITECTURE rtl OF txPacketGenerator IS

  -- Component Declarations
  COMPONENT fcn_controller
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          packetSize                      :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          transferReady                   :   IN    std_logic;  -- ufix1
          s_tdata_re                      :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          s_tvalid_re                     :   IN    std_logic;  -- ufix1
          m_tready_re                     :   IN    std_logic;  -- ufix1
          s_tdata_im                      :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          s_tvalid_im                     :   IN    std_logic;  -- ufix1
          m_tready_im                     :   IN    std_logic;  -- ufix1
          m_tdata_re                      :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
          m_tvalid_re                     :   OUT   std_logic;
          s_tready_re                     :   OUT   std_logic;
          m_tdata_im                      :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
          m_tvalid_im                     :   OUT   std_logic;
          s_tready_im                     :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fcn_controller
    USE ENTITY work.fcn_controller(rtl);

  -- Signals
  SIGNAL m_tdata_re_tmp                   : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL m_tdata_im_tmp                   : std_logic_vector(127 DOWNTO 0);  -- ufix128

BEGIN
  u_fcn_controller : fcn_controller
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              packetSize => packetSize,  -- uint16
              transferReady => transferReady,  -- ufix1
              s_tdata_re => s_tdata_re,  -- ufix128
              s_tvalid_re => s_tvalid_re,  -- ufix1
              m_tready_re => m_tready_re,  -- ufix1
              s_tdata_im => s_tdata_im,  -- ufix128
              s_tvalid_im => s_tvalid_im,  -- ufix1
              m_tready_im => m_tready_im,  -- ufix1
              m_tdata_re => m_tdata_re_tmp,  -- ufix128
              m_tvalid_re => m_tvalid_re,
              s_tready_re => s_tready_re,
              m_tdata_im => m_tdata_im_tmp,  -- ufix128
              m_tvalid_im => m_tvalid_im,
              s_tready_im => s_tready_im
              );

  ce_out <= clk_enable;

  m_tdata_re <= m_tdata_re_tmp;

  m_tdata_im <= m_tdata_im_tmp;

END rtl;

