import aerpawSiversDoc as doc
import collections

class siversDefaults():
    def __init__(self):
       
        self.freq = 122.88e6               # XO reference frequency
        self.fc = 28e9

        self.SPI_WR_RAW  = 0
        self.SPI_WR_CLR  = 1
        self.SPI_WR_NAND = 1
        self.SPI_WR_SET  = 2
        self.SPI_WR_OR   = 2
        self.SPI_WR_TGL  = 3
        self.SPI_WR_XOR  = 3
        self.SPI_RD      = 4

        self.RX_MODE   = 0
        self.TX_MODE   = 1
        self.TXRX_MODE = 2    
        
        self.regs_chronos = {
            'reg_00': { 'group':'rd-only', 'addr':0x0, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_01': { 'group':'rd-only', 'addr':0x1, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_02': { 'group':'rd-only', 'addr':0x2, 'size':3, 'value':0x000000, 'mask':0xFFFFF7},
            'reg_03': { 'group':'wr-only', 'addr':0x3, 'size':3, 'value':0x000000, 'mask':0xF0005F},
            'reg_04': { 'group':'wr-only', 'addr':0x4, 'size':3, 'value':0x000000, 'mask':0xF00FFF},
            'reg_05': { 'group':'wr-only', 'addr':0x5, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_06': { 'group':'wr-only', 'addr':0x6, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_07': { 'group':'wr-only', 'addr':0x7, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_08': { 'group':'wr-only', 'addr':0x8, 'size':3, 'value':0x000000, 'mask':0xFFFFFF},
            'reg_09': { 'group':'wr-only', 'addr':0x9, 'size':3, 'value':0x000000, 'mask':0xF7F8CF},
            'reg_10': { 'group':'wr-only', 'addr':0xA, 'size':3, 'value':0x000000, 'mask':0xF0FFFF},
        }

        # register fields from MSb downto LSb. Each tuple: name, width (bits)
        self.reg_fmt = [
            collections.OrderedDict( # reg_00
                [ ( 'addr',        4), 
                  ( 'axc_done',    1), 
                  ( 'axc',         1), 
                  ( 'atc',         1),
                  ( 'alc',         1),
                  ( 'res_crs',     6),
                  ( 'itail',       5),
                  ( 'alc_comp',    1),
                  ( 'atc_comp_hi', 1),
                  ( 'atc_comp_lo', 1),
                  ( 'atc_busy',    1),
                  ( 'alc_busy',    1),
                ]),

            collections.OrderedDict( # reg_01
                [ ( 'addr',                    4), 
                  ( 'wait_busy',               1), 
                  ( 'sac_busy',                1), 
                  ( 'fd_reg',                 10),
                  ( 'digital_design_version',  8),
                ]),

            collections.OrderedDict( # reg_02
                [ ( 'addr',         4), 
                  ( 'chip_id',      4), 
                  ( 'version',      4), 
                  ( 'spare inputs', 7),
                  ( 'ct_block',     1),
                  ( 'unused_00',    1),
                  ( 'pwr_alm',      1),
                  ( 'ld_out',       1),
                  ( 'main_busy',    1),
                ]),

            collections.OrderedDict( # reg_03
                [ ( 'addr',        4), 
                  ( 'unused_00',  13), 
                  ( 'ref_mode',    1), 
                  ( 'unused_01',   1),
                  ( 'en_chp',      1),
                  ( 'r_sel_ref',   2),
                  ( 'en_leak',     1),
                  ( 'divn_div8_9', 1),
                ]),        

            collections.OrderedDict( # reg_04
                [ ( 'addr',        4), 
                  ( 'unused_00',   8), 
                  ( 'order_sd',    2), 
                  ( 'nint_sd',    10),
                ]),        

            collections.OrderedDict( # reg_05
                [ ( 'addr',          4), 
                  ( 'frac_lsb_set',  4), 
                  ( 'frac_sd',      16),
                ]),        

            collections.OrderedDict( # reg_06
                [ ( 'addr',          4), 
                  ( 'spare_out',     7), 
                  ( 'dummy_dis',     1), 
                  ( 'out_pwr',       1),
                  ( 'pga_gain',      1),
                  ( 'pwr_alm_level', 3),
                  ( 'en_chp_ldo',    1),
                  ( 'testmux(6:5)',  2),
                  ( 'sft_rst_tgl',   1),
                  ( 'dis_d',         1),
                  ( 'nbits_d',       2),
                ]),

            collections.OrderedDict( # reg_07
                [ ( 'addr',         4), 
                  ( 'set_outvrnt',  2), 
                  ( 'dis_itprot',   1), 
                  ( 'ref_freq_stm', 2),
                  ( 'axc_tgl',      1),
                  ( 'retry_stm',    1),
                  ( 'atc_or',       1),
                  ( 'alc_or',       1),
                  ( 'atc(5:0)',     6),
                  ( 'alc',          5),
                ]),

            collections.OrderedDict( # reg_08
                [ ( 'addr',          4), 
                  ( 'en_amux',       1), 
                  ( 'sel_amux',      3), 
                  ( 'en_vtune',      1),
                  ( 'set_leak_chp',  3),
                  ( 'ld_en',         1),
                  ( 'mux_ctrl_ld',   3),
                  ( 'chp_set_tune',  3),
                  ( 'ichp_set(1:0)', 2),
                  ( 'chp_source',    1),
                  ( 'chp_sink',      1),
                  ( 'chp_test_en',   1),
                ]),

            collections.OrderedDict( # reg_09
                [ ( 'addr',           4), 
                  ( 'unused_00',      1), 
                  ( 'en_pfd',         1), 
                  ( 'en_iset_bias',   1),
                  ( 'iset_bias',      4),
                  ( 'spi_ld_stm_sel', 1),
                  ( 'aut_outamp',     1),
                  ( 'unused_01',      3),
                  ( 'en_x2_outamp',   1),
                  ( 'en_divn',        1),
                  ( 'unused_02',      2),
                  ( 'en_outamp',      1),
                  ( 'vco_en',         1),
                  ( 'atc(6)',         1),
                  ( 'ichp_set(2)',    1),      
                ]),

            collections.OrderedDict( # reg_10
                [ ( 'addr',        4), 
                  ( 'unused_00',   4), 
                  ( 'en_pwr_alm',  1), 
                  ( 'chp_delay',   2),
                  ( 'thr_alccomp', 4),
                  ( 'en_axctest',  1),
                  ( 'vlo_atccomp', 4),
                  ( 'vhi_atccomp', 4),
                ])
        ] # reg_fmt           
        
        
        self.regs =  {'chip_id':                 {'group':'system', 'addr':0x0000, 'size':4, 'value':0x02521910, 'mask':0xFFFFFFFF, 'doc':doc.chip_id_help},
                'chip_id_sw_en':           {'group':'system', 'addr':0x0004, 'size':1, 'value':0x00, 'mask':0x01, 'doc':doc.chip_id_sw_en_help},
                'fast_clk_ctrl':           {'group':'system', 'addr':0x0005, 'size':1, 'value':0x00, 'mask':0xF3, 'doc':doc.fast_clk_ctrl_help},
                'gpio_tx_rx_sw_ctrl':      {'group':'system', 'addr':0x0006, 'size':1, 'value':0x00, 'mask':0x13, 'doc':doc.gpio_tx_rx_sw_ctrl_help},
                'gpio_agc_rst_ctrl':       {'group':'system', 'addr':0x0007, 'size':1, 'value':0x00, 'mask':0x13, 'doc':doc.gpio_agc_rst_ctrl_help},
                'gpio_agc_start_ctrl':     {'group':'system', 'addr':0x0008, 'size':1, 'value':0x00, 'mask':0x13, 'doc':doc.gpio_agc_start_ctrl_help},
                'gpio_agc_gain_in_ctrl':   {'group':'system', 'addr':0x0009, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.gpio_agc_gain_in_ctrl_help},
                'gpio_agc_gain_out_ctrl':  {'group':'system', 'addr':0x000a, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.gpio_agc_gain_out_ctrl_help},
                'bist_amux_ctrl':          {'group':'system', 'addr':0x000b, 'size':1, 'value':0x00, 'mask':0xCF, 'doc':doc.bist_amux_ctrl_help},
                'bist_ot_ctrl':            {'group':'system', 'addr':0x000d, 'size':1, 'value':0x00, 'mask':0x33, 'doc':doc.bist_ot_ctrl_help},
                'bist_ot_temp':            {'group':'system', 'addr':0x000e, 'size':1, 'value':0x80, 'mask':0xDF, 'doc':doc.bist_ot_temp_help},
                'bist_ot_rx_off_mask':     {'group':'system', 'addr':0x000f, 'size':3, 'value':0x000000, 'mask':0x1FFFFF, 'doc':doc.bist_ot_rx_off_mask_help},
                'bist_ot_tx_off_mask':     {'group':'system', 'addr':0x0012, 'size':3, 'value':0x000000, 'mask':0x1FFFFF, 'doc':doc.bist_ot_tx_off_mask_help},
                'tx_dco_slope_offs':       {'group':'system', 'addr':0x001C, 'size':4, 'value':0xFF0000FF, 'mask':0xFFFFFFFF, 'doc':doc.tx_dco_slope_offs_help},
                #
                'bias_ctrl':               {'group':'bias',   'addr':0x0020, 'size':1, 'value':0x00, 'mask':0x7F, 'doc':doc.bias_ctrl_help},
                'bias_vco_x3':             {'group':'bias',   'addr':0x0021, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.bias_vco_x3_help},
                'bias_pll':                {'group':'bias',   'addr':0x0022, 'size':1, 'value':0x00, 'mask':0x37, 'doc':doc.bias_pll_help},
                'bias_lo':                 {'group':'bias',   'addr':0x0023, 'size':1, 'value':0x00, 'mask':0x3F, 'doc':doc.bias_lo_help},
                'bias_tx':                 {'group':'bias',   'addr':0x0024, 'size':2, 'value':0x0000, 'mask':0xFFFF, 'doc':doc.bias_tx_help},
                'bias_rx':                 {'group':'bias',   'addr':0x0026, 'size':2, 'value':0x0000, 'mask':0x0FFF, 'doc':doc.bias_rx_help},
                #
                'adc_ctrl':                {'group':'adc',    'addr':0x0040, 'size':1, 'value':0x00, 'mask':0xB7, 'doc':doc.adc_ctrl_help},
                'adc_clk_div':             {'group':'adc',    'addr':0x0041, 'size':1, 'value':0x03, 'mask':0xFF, 'doc':doc.adc_clk_div_help},
                'adc_sample_cycle':        {'group':'adc',    'addr':0x0042, 'size':1, 'value':0x00, 'mask':0x3F, 'doc':doc.adc_sample_cycle_help},
                'adc_num_samples':         {'group':'adc',    'addr':0x0043, 'size':1, 'value':0x00, 'mask':0x0F, 'doc':doc.adc_num_samples_help},
                'adc_sample':              {'group':'adc',    'addr':0x0050, 'size':2, 'value':0x000, 'mask':0x0FFF, 'doc':doc.adc_sample_help},
                'adc_mean':                {'group':'adc',    'addr':0x0052, 'size':2, 'value':0x000, 'mask':0x0FFF, 'doc':doc.adc_mean_help},
                'adc_max':                 {'group':'adc',    'addr':0x0054, 'size':2, 'value':0x000, 'mask':0x0FFF, 'doc':doc.adc_max_help},
                'adc_min':                 {'group':'adc',    'addr':0x0056, 'size':2, 'value':0x000, 'mask':0x0FFF, 'doc':doc.adc_min_help},
                'adc_diff':                {'group':'adc',    'addr':0x0058, 'size':2, 'value':0x0000, 'mask':0x1FFF, 'doc':doc.adc_diff_help},
                #
                'pll_en':                  {'group':'pll',    'addr':0x0060, 'size':1, 'value':0x00, 'mask':0x7F, 'doc':doc.pll_en_help},
                'pll_divn':                {'group':'pll',    'addr':0x0061, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.pll_divn_help},
                'pll_pfd':                 {'group':'pll',    'addr':0x0062, 'size':1, 'value':0x00, 'mask':0x07, 'doc':doc.pll_pfd_help},
                'pll_chp':                 {'group':'pll',    'addr':0x0063, 'size':1, 'value':0x00, 'mask':0x73, 'doc':doc.pll_chp_help},
                'pll_ld_mux_ctrl':         {'group':'pll',    'addr':0x0064, 'size':1, 'value':0x10, 'mask':0x37, 'doc':doc.pll_ld_mux_ctrl_help},
                'pll_test_mux_in':         {'group':'pll',    'addr':0x0065, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.pll_test_mux_in_help},
                'pll_ref_in_lvds_en':      {'group':'pll',    'addr':0x0066, 'size':1, 'value':0x02, 'mask':0x03, 'doc':doc.pll_ref_in_lvds_en_help},
                'pll_sd_ctrl':             {'group':'pll',    'addr':0x0067, 'size':1, 'value':0x00, 'mask':0x77, 'doc':doc.pll_sd_ctrl_help},
                'pll_sd_cfg':              {'group':'pll',    'addr':0x0068, 'size':1, 'value':0x00, 'mask':0x33, 'doc':doc.pll_sd_cfg_help},
                'pll_sd_k':                {'group':'pll',    'addr':0x0069, 'size':3, 'value':0x00, 'mask':0xFFFFFF, 'doc':doc.pll_sd_k_help},
                'pll_sd_num':              {'group':'pll',    'addr':0x006c, 'size':2, 'value':0x00, 'mask':0xFFFF, 'doc':doc.pll_sd_num_help},
                'pll_sd_den':              {'group':'pll',    'addr':0x006e, 'size':2, 'value':0x00, 'mask':0xFFFF, 'doc':doc.pll_sd_den_help},
                #
                'vco_en':                  {'group':'vco',    'addr':0x0080, 'size':1, 'value':0x00, 'mask':0x7F, 'doc':doc.vco_en_help},
                'vco_dig_tune':            {'group':'vco',    'addr':0x0081, 'size':1, 'value':0x00, 'mask':0x7F, 'doc':doc.vco_dig_tune_help},
                'vco_ibias':               {'group':'vco',    'addr':0x0082, 'size':1, 'value':0x00, 'mask':0x3F, 'doc':doc.vco_ibias_help},
                'vco_vtune_ctrl':          {'group':'vco',    'addr':0x0083, 'size':1, 'value':0x00, 'mask':0x17, 'doc':doc.vco_vtune_ctrl_help},
                'vco_atc_del':             {'group':'vco',    'addr':0x0084, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_atc_del_help},
                'vco_amux_ctrl':           {'group':'vco',    'addr':0x0085, 'size':1, 'value':0x00, 'mask':0x1F, 'doc':doc.vco_amux_ctrl_help},
                'vco_vtune_th':            {'group':'vco',    'addr':0x0086, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_vtune_th_help},
                'vco_atc_hi_th':           {'group':'vco',    'addr':0x0087, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_atc_hi_th_help},
                'vco_atc_lo_th':           {'group':'vco',    'addr':0x0088, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_atc_lo_th_help},
                'vco_alc_hi_th':           {'group':'vco',    'addr':0x0089, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_alc_hi_th_help},
                'vco_override_ctrl':       {'group':'vco',    'addr':0x008A, 'size':2, 'value':0x00, 'mask':0x01FF, 'doc':doc.vco_override_ctrl_help},
                'vco_alc_del':             {'group':'vco',    'addr':0x008C, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_alc_del_help},
                'vco_vtune_del':           {'group':'vco',    'addr':0x008D, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_vtune_del_help},
                'vco_tune_loop_del':       {'group':'vco',    'addr':0x008E, 'size':3, 'value':0x00, 'mask':0x03FFFF, 'doc':doc.vco_tune_loop_del_help},
                'vco_atc_vtune_set_del':   {'group':'vco',    'addr':0x0091, 'size':3, 'value':0x00, 'mask':0x03FFFF, 'doc':doc.vco_atc_vtune_set_del_help},
                'vco_atc_vtune_unset_del': {'group':'vco',    'addr':0x0094, 'size':3, 'value':0x00, 'mask':0x03FFFF, 'doc':doc.vco_atc_vtune_unset_del_help},
                'vco_tune_ctrl':           {'group':'vco',    'addr':0x0097, 'size':1, 'value':0x00, 'mask':0x77, 'doc':doc.vco_tune_ctrl_help},
                'vco_tune_fd_cfg':         {'group':'vco',    'addr':0x0098, 'size':1, 'value':0x10, 'mask':0xFF, 'doc':doc.vco_tune_fd_cfg_help},
                'vco_tune_fd_polarity':    {'group':'vco',    'addr':0x0099, 'size':1, 'value':0x11, 'mask':0xF1, 'doc':doc.vco_tune_fd_polarity_help},
                'vco_tune_status':         {'group':'vco',    'addr':0x00A0, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.vco_tune_status_help},
                'vco_tune_det_status':     {'group':'vco',    'addr':0x00A1, 'size':1, 'value':0x00, 'mask':0x0F, 'doc':doc.vco_tune_det_status_help},
                'vco_tune_freq_cnt':       {'group':'vco',    'addr':0x00A2, 'size':4, 'value':0x00, 'mask':0x01FFFFFF, 'doc':doc.vco_tune_freq_cnt_help},
                'vco_tune_dig_tune':       {'group':'vco',    'addr':0x00A6, 'size':1, 'value':0x40, 'mask':0x7F, 'doc':doc.vco_tune_dig_tune_help},
                'vco_tune_ibias':          {'group':'vco',    'addr':0x00A7, 'size':1, 'value':0x00, 'mask':0x3F, 'doc':doc.vco_tune_ibias_help},
                'vco_tune_vtune':          {'group':'vco',    'addr':0x00A8, 'size':1, 'value':0x80, 'mask':0xFF, 'doc':doc.vco_tune_vtune_help},
                #
                'tx_ctrl':                 {'group':'tx',     'addr':0x00C0, 'size':1, 'value':0x10, 'mask':0x7F, 'doc':doc.tx_ctrl_help},
                'tx_bb_q_dco':             {'group':'tx',     'addr':0x00C1, 'size':1, 'value':0x40, 'mask':0x7F, 'doc':doc.tx_bb_q_dco_help},
                'tx_bb_i_dco':             {'group':'tx',     'addr':0x00C2, 'size':1, 'value':0x40, 'mask':0x7F, 'doc':doc.tx_bb_i_dco_help},
                'tx_bb_phase':             {'group':'tx',     'addr':0x00C3, 'size':1, 'value':0x00, 'mask':0x1F, 'doc':doc.tx_bb_phase_help},
                'tx_bb_gain':              {'group':'tx',     'addr':0x00C4, 'size':1, 'value':0x00, 'mask':0x23, 'doc':doc.tx_bb_gain_help},
                'tx_bb_iq_gain':           {'group':'tx',     'addr':0x00C5, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_bb_iq_gain_help},
                'tx_bfrf_gain':            {'group':'tx',     'addr':0x00C6, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_bfrf_gain_help},
                'tx_bf_pdet_mux':          {'group':'tx',     'addr':0x00C7, 'size':1, 'value':0x00, 'mask':0xBF, 'doc':doc.tx_bf_pdet_mux_help},
                'tx_alc_ctrl':             {'group':'tx',     'addr':0x00C8, 'size':1, 'value':0x00, 'mask':0xF3, 'doc':doc.tx_alc_ctrl_help},
                'tx_alc_loop_cnt':         {'group':'tx',     'addr':0x00C9, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_alc_loop_cnt_help},
                'tx_alc_start_delay':      {'group':'tx',     'addr':0x00CA, 'size':2, 'value':0x0000, 'mask':0xFFFF, 'doc':doc.tx_alc_start_delay_help},
                'tx_alc_meas_delay':       {'group':'tx',     'addr':0x00CC, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_alc_meas_delay_help},
                'tx_alc_bfrf_gain_max':    {'group':'tx',     'addr':0x00CD, 'size':1, 'value':0xFF, 'mask':0xFF, 'doc':doc.tx_alc_bfrf_gain_max_help},
                'tx_alc_bfrf_gain_min':    {'group':'tx',     'addr':0x00CE, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_alc_bfrf_gain_min_help},
                'tx_alc_step_max':         {'group':'tx',     'addr':0x00CF, 'size':1, 'value':0x00, 'mask':0x33, 'doc':doc.tx_alc_step_max_help},
                'tx_alc_pdet_lo_th':       {'group':'tx',     'addr':0x00D0, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_alc_pdet_lo_th_help},
                'tx_alc_pdet_hi_offs_th':  {'group':'tx',     'addr':0x00D1, 'size':1, 'value':0x00, 'mask':0x1F, 'doc':doc.tx_alc_pdet_hi_offs_th_help},
                'tx_alc_bfrf_gain':        {'group':'tx',     'addr':0x00D2, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.tx_alc_bfrf_gain_help},
                'tx_alc_pdet':             {'group':'tx',     'addr':0x00D3, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.tx_alc_pdet_help},
                #
                'rx_gain_ctrl_mode':       {'group':'rx',     'addr':0x00E0, 'size':1, 'value':0x00, 'mask':0x3B, 'doc':doc.rx_gain_ctrl_mode_help},
                'rx_gain_ctrl_reg_index':  {'group':'rx',     'addr':0x00E1, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_gain_ctrl_reg_index_help},
                'rx_gain_ctrl_sel':        {'group':'rx',     'addr':0x00E2, 'size':2, 'value':0x0000, 'mask':0x03FF, 'doc':doc.rx_gain_ctrl_sel_help},
                'rx_gain_ctrl_bfrf':       {'group':'rx',     'addr':0x00E4, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_gain_ctrl_bfrf_help},
                'rx_gain_ctrl_bb1':        {'group':'rx',     'addr':0x00E5, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_gain_ctrl_bb1_help},
                'rx_gain_ctrl_bb2':        {'group':'rx',     'addr':0x00E6, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_gain_ctrl_bb2_help},
                'rx_gain_ctrl_bb3':        {'group':'rx',     'addr':0x00E7, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_gain_ctrl_bb3_help},
                'rx_bb_q_dco':             {'group':'rx',     'addr':0x00E8, 'size':2, 'value':0x40, 'mask':0x337F, 'doc':doc.rx_bb_q_dco_help},
                'rx_bb_i_dco':             {'group':'rx',     'addr':0x00EA, 'size':2, 'value':0x40, 'mask':0x337F, 'doc':doc.rx_bb_i_dco_help},
                'rx_bb_drv_q_dco':         {'group':'rx',     'addr':0x00EC, 'size':2, 'value':0x3F, 'mask':0x037F, 'doc':doc.rx_bb_drv_q_dco_help},
                'rx_bb_drv_i_dco':         {'group':'rx',     'addr':0x00EE, 'size':2, 'value':0x3F, 'mask':0x037F, 'doc':doc.rx_bb_drv_i_dco_help},
                'rx_dco_en':               {'group':'rx',     'addr':0x00F0, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.rx_dco_en_help},
                'rx_bb_biastrim':          {'group':'rx',     'addr':0x00F1, 'size':1, 'value':0x00, 'mask':0x3F, 'doc':doc.rx_bb_biastrim_help},
                'rx_bb_test_ctrl':         {'group':'rx',     'addr':0x00F2, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.rx_bb_test_ctrl_help},
                #
                'agc_int_ctrl':            {'group':'agc',    'addr':0x0100, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.agc_int_ctrl_help},
                'agc_int_en_ctrl':         {'group':'agc',    'addr':0x0101, 'size':1, 'value':0x20, 'mask':0x1F, 'doc':doc.agc_int_en_ctrl_help},
                'agc_int_backoff':         {'group':'agc',    'addr':0x0102, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.agc_int_backoff_help},
                'agc_int_start_del':       {'group':'agc',    'addr':0x0103, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.agc_int_start_del_help},
                'agc_int_timeout':         {'group':'agc',    'addr':0x0104, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.agc_int_timeout_help},
                'agc_int_gain_change_del': {'group':'agc',    'addr':0x0105, 'size':1, 'value':0x05, 'mask':0x0F, 'doc':doc.agc_int_gain_change_del_help},
                'agc_int_pdet_en':         {'group':'agc',    'addr':0x0106, 'size':1, 'value':0x09, 'mask':0x0F, 'doc':doc.agc_int_pdet_en_help},
                'agc_int_pdet_filt':       {'group':'agc',    'addr':0x0107, 'size':2, 'value':0x1F1F, 'mask':0x1FFF, 'doc':doc.agc_int_pdet_filt_help},
                'agc_int_pdet_th':         {'group':'agc',    'addr':0x0109, 'size':5, 'value':0x0000000000, 'mask':0xFFFFFFFFFF, 'doc':doc.agc_int_pdet_th_help},
                'agc_int_bfrf_gain_lvl':   {'group':'agc',    'addr':0x010E, 'size':4, 'value':0xFFCC9966, 'mask':0xFFFFFFFF, 'doc':doc.agc_int_bfrf_gain_lvl_help},
                'agc_int_bb3_gain_lvl':    {'group':'agc',    'addr':0x0112, 'size':3, 'value':0xFCA752, 'mask':0xFFFFFF, 'doc':doc.agc_int_bb3_gain_lvl_help},
                'agc_int_status_pdet':     {'group':'agc',    'addr':0x0115, 'size':2, 'value':0xF4, 'mask':0x1FFF, 'doc':doc.agc_int_status_pdet_help},
                'agc_int_status':          {'group':'agc',    'addr':0x0117, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.agc_int_status_help},
                'agc_int_gain':            {'group':'agc',    'addr':0x0118, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.agc_int_gain_help},
                'agc_int_gain_setting':    {'group':'agc',    'addr':0x0119, 'size':4, 'value':0xFFFFFFFF, 'mask':0xFFFFFFFF, 'doc':doc.agc_int_gain_setting_help},
                'agc_ext_ctrl':            {'group':'agc',    'addr':0x011D, 'size':1, 'value':0x05, 'mask':0x07, 'doc':doc.agc_ext_ctrl_help},
                #
                'trx_ctrl':                {'group':'trx',    'addr':0x01E0, 'size':1, 'value':0x00, 'mask':0x3B, 'doc':doc.trx_ctrl_help},
                'trx_soft_ctrl':           {'group':'trx',    'addr':0x01E1, 'size':1, 'value':0x00, 'mask':0x03, 'doc':doc.trx_soft_ctrl_help},
                'trx_soft_delay':          {'group':'trx',    'addr':0x01E2, 'size':1, 'value':0x00, 'mask':0x07, 'doc':doc.trx_soft_delay_help},
                'trx_soft_max_state':      {'group':'trx',    'addr':0x01E3, 'size':1, 'value':0x00, 'mask':0x07, 'doc':doc.trx_soft_max_state_help},
                'trx_tx_on':               {'group':'trx',    'addr':0x01E4, 'size':3, 'value':0x1FFFFF, 'mask':0x1FFFFF, 'doc':doc.trx_tx_on_help},
                'trx_tx_off':              {'group':'trx',    'addr':0x01E7, 'size':3, 'value':0x00, 'mask':0x1FFFFF, 'doc':doc.trx_tx_off_help},
                'trx_rx_on':               {'group':'trx',    'addr':0x01EA, 'size':3, 'value':0x1FFFFF, 'mask':0x1FFFFF, 'doc':doc.trx_rx_on_help},
                'trx_rx_off':              {'group':'trx',    'addr':0x01ED, 'size':3, 'value':0x00, 'mask':0x1FFFFF, 'doc':doc.trx_rx_off_help},
                'trx_soft_tx_on_enables':  {'group':'trx',    'addr':0x0200, 'size':8, 'value':0x00, 'mask':0x1F1F1F1F1F1F1F1F, 'doc':doc.trx_soft_tx_on_enables_help},
                'trx_soft_rx_on_enables':  {'group':'trx',    'addr':0x0208, 'size':8, 'value':0x00, 'mask':0x1F1F1F1F1F1F1F1F, 'doc':doc.trx_soft_rx_on_enables_help},
                'trx_soft_bf_on_grp_sel':  {'group':'trx',    'addr':0x0210, 'size':4, 'value':0x00, 'mask':0xFFFFFFFF, 'doc':doc.trx_soft_bf_on_grp_sel_help},
                #
                'reg_00':                  {'group':'stash',  'addr':0x0220, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_01':                  {'group':'stash',  'addr':0x0221, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_02':                  {'group':'stash',  'addr':0x0222, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_03':                  {'group':'stash',  'addr':0x0223, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_04':                  {'group':'stash',  'addr':0x0224, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_05':                  {'group':'stash',  'addr':0x0225, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_06':                  {'group':'stash',  'addr':0x0226, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_07':                  {'group':'stash',  'addr':0x0227, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_08':                  {'group':'stash',  'addr':0x0228, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_09':                  {'group':'stash',  'addr':0x0229, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_10':                  {'group':'stash',  'addr':0x022A, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_11':                  {'group':'stash',  'addr':0x022B, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_12':                  {'group':'stash',  'addr':0x022C, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_13':                  {'group':'stash',  'addr':0x022D, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_14':                  {'group':'stash',  'addr':0x022E, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_15':                  {'group':'stash',  'addr':0x022F, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_16':                  {'group':'stash',  'addr':0x0230, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_17':                  {'group':'stash',  'addr':0x0231, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_18':                  {'group':'stash',  'addr':0x0232, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_19':                  {'group':'stash',  'addr':0x0233, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_20':                  {'group':'stash',  'addr':0x0234, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_21':                  {'group':'stash',  'addr':0x0235, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_22':                  {'group':'stash',  'addr':0x0236, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_23':                  {'group':'stash',  'addr':0x0237, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_24':                  {'group':'stash',  'addr':0x0238, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_25':                  {'group':'stash',  'addr':0x0239, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_26':                  {'group':'stash',  'addr':0x023A, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_27':                  {'group':'stash',  'addr':0x023B, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_28':                  {'group':'stash',  'addr':0x023C, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_29':                  {'group':'stash',  'addr':0x023D, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_30':                  {'group':'stash',  'addr':0x023E, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
                'reg_31':                  {'group':'stash',  'addr':0x023F, 'size':1, 'value':0x00, 'mask':0xFF, 'doc':doc.reg_00_help},
               
                'bf_tx_awv_idx_table':   {'group':'bf_tx', 'addr':0x0120, 'size':64, 'value':0x00},
                'bf_tx_awv_idx':         {'group':'bf_tx', 'addr':0x0160, 'size':1,  'value':0x00},
                'bf_tx_awv_ce':          {'group':'bf_tx', 'addr':0x0161, 'size':1,  'value':0x00},
                'bf_tx_cfg':             {'group':'bf_tx', 'addr':0x0163, 'size':1,  'value':0x01},
                #
                'bf_rx_awv_idx_table':   {'group':'bf_rx', 'addr':0x0180, 'size':64, 'value':0x00},
                'bf_rx_awv_idx':         {'group':'bf_rx', 'addr':0x01C0, 'size':1,  'value':0x00},
                'bf_rx_awv_ce':          {'group':'bf_rx', 'addr':0x01C1, 'size':1,  'value':0x00},
                'bf_rx_cfg':             {'group':'bf_rx', 'addr':0x01C3, 'size':1,  'value':0x01},

                'bf_tx_mbist_0_pat':     {'group':'bf_tx', 'addr':0x0164, 'size':2, 'value':0x5555},
                'bf_tx_mbist_1_pat':     {'group':'bf_tx', 'addr':0x0166, 'size':2, 'value':0xaaaa},
                'bf_tx_mbist_2p_sel':    {'group':'bf_tx', 'addr':0x0169, 'size':1, 'value':0x00},
                'bf_tx_mbist_en':        {'group':'bf_tx', 'addr':0x016a, 'size':2, 'value':0x0000},
                'bf_tx_mbist_result':    {'group':'bf_tx', 'addr':0x016c, 'size':2, 'value':0x0000},
                'bf_tx_mbist_done':      {'group':'bf_tx', 'addr':0x016e, 'size':2, 'value':0x0000},
                #
                'bf_rx_mbist_0_pat':     {'group':'bf_rx', 'addr':0x01C4, 'size':2, 'value':0x5555},
                'bf_rx_mbist_1_pat':     {'group':'bf_rx', 'addr':0x01C6, 'size':2, 'value':0xaaaa},
                'bf_rx_mbist_2p_sel':    {'group':'bf_rx', 'addr':0x01C9, 'size':1, 'value':0x00},
                'bf_rx_mbist_en':        {'group':'bf_rx', 'addr':0x01Ca, 'size':2, 'value':0x0000},
                'bf_rx_mbist_result':    {'group':'bf_rx', 'addr':0x01Cc, 'size':2, 'value':0x0000},
                'bf_rx_mbist_done':      {'group':'bf_rx', 'addr':0x01Ce, 'size':2, 'value':0x0000},

                'bf_tx_awv_ptr':         {'group':'bf_tx', 'addr':0x0162, 'size':1,  'value':0x00},
                'bf_rx_awv_ptr':         {'group':'bf_rx', 'addr':0x01C2, 'size':1,  'value':0x00},
                'bf_tx_awv':             {'group':'bf_tx', 'addr':0x0800, 'size':64*32, 'value':0x0000},
                'bf_rx_awv':             {'group':'bf_rx', 'addr':0x1000, 'size':64*32, 'value':0x0000},                    
           }
        
        
        

     